"""add FK to suip_data

Revision ID: 709af6d1370b
Revises: 
Create Date: 2025-07-03 22:02:13.435905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709af6d1370b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suip_data', sa.Column('parsed_file_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'suip_data', 'parsed_file', ['parsed_file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suip_data', type_='foreignkey')
    op.drop_column('suip_data', 'parsed_file_id')
    # ### end Alembic commands ###
