"""add mimetype to parsed_file

Revision ID: 8406385a870f
Revises: 709af6d1370b
Create Date: 2025-07-03 22:04:50.373859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8406385a870f'
down_revision: Union[str, Sequence[str], None] = '709af6d1370b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_file', sa.Column('mimetype', sa.String(), nullable=True))
    op.drop_column('parsed_file', 'filetype')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_file', sa.Column('filetype', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('parsed_file', 'mimetype')
    # ### end Alembic commands ###
